name: Build C++ Application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile Program
        run: g++ main.cpp -o myapp

      - name: Run Program
        run: ./myapp